/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.media[_ngcontent-%COMP%] { \n    margin-bottom: 30px;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovV2ViL015UHJvamVjdC9UcmFpbmluZy9Bbmd1bGFyL1RoZS1Db21wbGV0ZS1Bbmd1bGFyLUNvdXJzZS1CZWdpbm5lci10by1BZHZhbmNlZC9kZXBsb3ktZGVtby9zcmMvYXBwL2dpdGh1Yi1mb2xsb3dlcnMvZ2l0aHViLWZvbGxvd2Vycy5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L1dlYi9NeVByb2plY3QvVHJhaW5pbmcvQW5ndWxhci9UaGUtQ29tcGxldGUtQW5ndWxhci1Db3Vyc2UtQmVnaW5uZXItdG8tQWR2YW5jZWQvZGVwbG95LWRlbW8vc3JjL2FwcC9naXRodWItZm9sbG93ZXJzL2dpdGh1Yi1mb2xsb3dlcnMuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
